[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  ADMIN_PASSWORD = "🔑 รหัสผ่านเข้าหลังบ้านแอดมิน"
  XENDIT_SECRET_KEY = "💳 คีย์ธุรกรรม Xendit Secret Key API"
  XENDIT_WEBHOOK_TOKEN = "🔗 คีย์ตรวจสอบข้อมูล Webhook Token ของ Xendit"
  TURNSTILE_SITE_KEY = "🔒 คีย์ระบุโดเมน Cloudflare Turnstile Site Key"
  TURNSTILE_SECRET_KEY = "🛡️ คีย์ตรวจสอบความเป็นมนุษย์ Cloudflare Turnstile Secret Key"
  STREAMLABS_ACCESS_TOKEN = "📽️ คีย์แจ้งเตือนขึ้นจอ Streamlabs Access Token API"
  STREAMELEMENTS_JWT = "📽️ (Optional) คีย์แจ้งเตือนขึ้นจอ StreamElements JWT"
  STREAMELEMENTS_CHANNEL_ID = "🆔 (Optional) รหัสช่องสตรีม Streamelements ID"