[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  ADMIN_EMAILS = "Google account for admin (vtuber.main@gmail.com, graphic.designer@gmail.com, moderator.team@gmail.com)"
  BEAM_API_KEY = "[REDACTED]"
  BEAM_WEBHOOK_SECRET = "[REDACTED]"
  BEAM_API_URL = "https://playground.api.beamcheckout.com"
  TURNSTILE_SITE_KEY = "[REDACTED]"
  TURNSTILE_SECRET_KEY = "[REDACTED]"
  STREAMLABS_ACCESS_TOKEN = "[REDACTED]"
  STREAMELEMENTS_JWT = "[REDACTED]"
  STREAMELEMENTS_CHANNEL_ID = "[REDACTED]"