#:schema node_modules/wrangler/config-schema.json
name = "tips-secure"

main = "src/worker.ts"
compatibility_date = "2026-06-16"

[assets]
directory = "./dist"
binding = "ASSETS"

not_found_handling = "single-page-application"